---
- hosts: master 
  vars:
  tasks:
    - name: Capturing DNSMasq DHCP Leases
      shell: cat /var/lib/misc/dnsmasq.leases | awk '{ print $4,$3,$2 }'
      register: _dnsmasq_dhcp_leases
      changed_when: false

    - name: Updating {{ inventory_dir }}
      template:
        src: oneHost.ini.j2
        dest: "oneHost.ini"
      delegate_to: localhost
      become: false
