---

- name: Read node-token from master
  slurp:
    src: /var/lib/rancher/k3s/server/node-token
  register: node_token

- name: Store Master node-token
  set_fact: 
   token: "{{ node_token.content | b64decode | regex_replace('\n', '') }}"
